name: CD
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.9.0 
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Publish
        run: dotnet publish ./API_Restaurants/API_Restaurants.csproj  -c Release -o ${{ env.DOTNET_ROOT }}/api
      - name: upload artifact
        uses: actions/upload-artifact@v2.2.4
        with: 
         name: api-artifact
         path: ${{ env.DOTNET_ROOT }}/api

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Dev'
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }}
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: api-artifact
      - name: Azure WebApp deploy
        id: deploy-to-azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'restaurantsapi-dev'
          publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV }}
          
  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: api-artifact
      - name: Azure WebApp deploy
        id: deploy-to-azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'restaurantsapi-prod'
          publish-profile: ${{ secrets.PUBLISH_PROFILE_PROD }}
